name: CI Back Quarkus

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Start Docker dependencies
        run: docker-compose up -d
        working-directory: ./doodlestudent-main/api

      - name: Wait for services (sleep)
        run: sleep 15

      - name: Build with Maven (including tests)
        run: ./mvnw clean package
        working-directory: ./api

      - name: Run tests
        run: ./mvnw test
        working-directory: ./api

      - name: Stop Docker dependencies
        run: docker-compose down
        working-directory: ./api
