name: CI Front Angular

on:
  push:
    branches: [ main ]
    paths: 
      - 'front/**'
      - '.github/workflows/ci-front.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'front/**'
  workflow_dispatch:

jobs:
  test:
    name: Tests Front Angular
    runs-on: ubuntu-latest

    defaults:
          run:
            working-directory: ./doodlestudent-main/front

    steps:

    # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

    # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

    # Install dependencies
      - name: Install dependencies
        run: npm ci
        
    # Build the project
      - name: Build the project
        run: npx ng build
      
    # Running unit tests
      - name: Running unit tests 
        run : npx ng test --watch=false --browsers=ChromeHeadless

      
    


    
    
    
    
